# Generated by Django 4.1.1 on 2022-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_phone', models.IntegerField(max_length=255)),
                ('customer_email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('nom_complet', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
