# Generated by Django 4.1.1 on 2022-09-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom_complet',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_phone',
        ),
        migrations.AlterField(
            model_name='produit',
            name='total_amount',
            field=models.IntegerField(),
        ),
    ]
